version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "03:00"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "main"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable27
  schedule:
    interval: weekly
    day: saturday
    time: "03:10"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable27"


- package-ecosystem: composer
  directory: "/"
  target-branch: stable26
  schedule:
    interval: weekly
    day: saturday
    time: "03:20"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable26"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable25
  schedule:
    interval: weekly
    day: saturday
    time: "03:30"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable25"

- package-ecosystem: composer
  directory: "/"
  target-branch: stable24
  schedule:
    interval: weekly
    day: saturday
    time: "03:40"
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-major"]
  labels:
    - "dependencies"
    - "stable24"

